language: go
go_import_path: github.com/ng-vu/goconveyx
go:
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - tip
sudo: false
install:
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure
    - go get github.com/alecthomas/gometalinter
    - gometalinter --install
script:
    - export PATH=$PATH:$HOME/gopath/bin
    - export GORACE="halt_on_error=1"
    - test -z "$(gometalinter --disable-all
      --enable=gofmt
      --enable=golint
      --enable=vet
      --enable=gosimple
      --enable=unconvert
      --deadline=4m . | tee /dev/stderr)"
    - go test -v -race .
    - go test -v -race . -covermode=atomic -coverprofile=profile.cover
after_success:
    - go get -v github.com/mattn/goveralls
    - goveralls -coverprofile=profile.cover -service=travis-ci
